FROM sensu-base

COPY config/sensu/* /etc/sensu/conf.d/
EXPOSE 3030
EXPOSE 4567
CMD /opt/sensu/bin/sensu-service start server fork && /opt/sensu/bin/sensu-service start api fork && /opt/sensu/bin/sensu-service start client fork && tail -f /var/log/sensu/sensu-*.log

